runtime: java11
service: backend

instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 10
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50